random_seed: 444

dataset:
  type: &dataset_type 'KITTI'
  root_dir: 'datasets/Rope3D'
  train_split: 'train'
  test_split: 'test'
  batch_size: 8
  use_3d_center: True
  class_merging: False
  use_dontcare: False
  bbox2d_type: 'anno'
  meanshape: False
  writelist: ['Car']
  clip_2d: False

  aug_pd: True
  aug_crop: True

  random_flip: 0.5
  random_crop: 0.5
  scale: 0.05
  shift: 0.05

  depth_scale: 'normal'


model_name: 'roadsurf'
model:
  use_roadsurf: True
  num_classes: 4
  return_intermediate_dec: True
  device: 'cuda'

  backbone: 'resnet50'
  train_backbone: True
  num_feature_levels: 4
  dilation: False
  position_embedding: 'sine'
  masks: False

  mode: LID
  num_depth_bins: 80
  depth_min: 1e-3
  depth_max: 60.0

  with_box_refine: True
  two_stage: False
  use_dab: False
  use_dn: False
  two_stage_dino: False
  init_box: False
  enc_layers: 3
  dec_layers: 3
  hidden_dim: 256
  dim_feedforward: 256
  dropout: 0.1
  nheads: 8
  num_queries: 50
  enc_n_points: 4
  dec_n_points: 4
  scalar: 5
  label_noise_scale: 0.2
  box_noise_scale: 0.4
  num_patterns: 0
  aux_loss: True

  cls_loss_coef: 2
  focal_alpha: 0.25

  bbox_loss_coef: 5
  giou_loss_coef: 2
  3dcenter_loss_coef: 10
  dim_loss_coef: 1
  angle_loss_coef: 1
  depth_loss_coef: 1
  depth_map_loss_coef: 1

  set_cost_class: 2
  set_cost_bbox: 5
  set_cost_giou: 2
  set_cost_3dcenter: 10

  road:
    xbound: [-30.0, 30.0, 0.5]
    zbound: [0.0, 80.0, 0.5]
    feat_level: 1
    road_channels: 128
    road_num_convs: 3
    plane_solve_axis: beta   # 'beta' or 'gamma'，默认解 y 高度
    data_loss_coef: 1.0
    smooth_loss_coef: 0.2
    plane_loss_coef: 0.05
    consistency_loss_coef: 1.0


optimizer:
  type: 'adamw'
  lr: 0.0002
  weight_decay: 0.0001

lr_scheduler:
  type: 'step'
  warmup: False
  decay_rate: 0.1
  decay_list: [125, 165]

trainer:
  max_epoch: 195
  gpu_ids: '1'
  save_frequency: 1
  # resume_model: True
  # pretrain_model: '/home/ubuntu/code/RoadSurf/outputs/roadsurf/checkpoint.pth'
  save_path: 'outputs/'
  save_all: False
  use_dn: False
  scalar: 5
  label_noise_scale: 0.2
  box_noise_scale: 0.4
  num_patterns: 0

tester:
  type: *dataset_type
  mode: single
  checkpoint: 195
  threshold: 0.2
  topk: 50

